### ISSUE TITLE
Blocks Discordsrv :(

### ISSUE THREAD

**Issue by thecenters** [KvinneKraft/DashSociety#1]
Great plugin. Unfortunately it blocks Discordsrv from sending chat messages from discord to the in game chat. Is this something you could add a fix for?

**Comment by KvinneKraft** [comment]
Hey there, thank you for sending me a bug report.

What plugin are you talking about exactly? And are you certain of my plugin being the cause?

I hope to receive a reply from you shortly. Once I know a bit more about the issue that you are facing (assuming that the issue has to do with one of my plugins), will I be able to apply a fix.

-Kind regards, Dashie

-------- Original Message --------

**Comment by thecenters** [comment]
This is the plugin https://www.spigotmc.org/resources/discordsrv.18494/

It seems as your plugin blocks this plugin from sending anything to the in-game chat (unless it uses broadcast)

**Comment by KvinneKraft** [comment]
Thank you for your reply.

Would you perhaps mind giving me the following information?

- Your server version (1.13, 1.15, 1.8 ect)

-Kind regards, Dashie
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thecenters** [comment]
Paper 1.15.2

**Comment by KvinneKraft** [comment]
Thank you very much, after some looking around have I found the cause of this issue. I am going to fix it straight ahead and post an updated version on my spigot page.

I am also likely to revamp the entire Dash Captcha plugin very soon, so you may want to stick around.

Have a nice day and or night, blessed be ) o (

-Kind regards, Dashie

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thecenters** [comment]
When will you post this fix for Discordsrv? I would like to try it

**Comment by KvinneKraft** [comment]
I had already posted it. 10 minutes after I had replied to you, yesterday.

-------- Original Message --------
