### ISSUE TITLE
I couldn't find a way to contact you.

### ISSUE THREAD

**Issue by thecenters** [KvinneKraft/DashSociety#3]
With Better Captcha, is there a permission I can give people so they don't have to ender the captcha?

**Comment by KvinneKraft** [comment]
Hey there, thank you for reaching out to me. I am sorry about the difficulty thus far. There are several permissions that come with the plugin including one that allows you to bypass the restrictions. You may check the config.yml for the permissions, you can also change them if you prefer. When you have changed your config.yml you may reload the plugin directly (/bettercaptcha reload) or restart the server in order for the plugin to recognize the new config.

If you need any more help, just reply to this email, kind regards,
-Dashie

-------- Original Message --------

**Comment by thecenters** [comment]
I looked in the config for permissions, but I only see permissions for specific sounds or fireworks. I don't see anything about bypassing captcha.

**Comment by KvinneKraft** [comment]
Are you sure that you are using the latest version of the Captcha plugin? The latest version is 2.1 going by the name "Dashies Better Captcha [RECODED]". If you are not using this version then I would recommend heading over to my spigot and checking my latest resource posts, it should be in there. It comes with many more features, the older version also has a description that says this.

Kind regards,
-Dashie

-------- Original Message --------

**Comment by thecenters** [comment]
yes i am using that version

**Comment by KvinneKraft** [comment]
I will dig into the code tomorrow, expect an update within a week or so.

-Dashie
-------- Original Message --------
